name: learn_jp
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^1.6.5
  cupertino_icons: ^0.1.2
  provider: ^4.0.4
  flutter_icons: ^1.0.0+1
  carousel_slider: ^1.4.1
  cloud_firestore: ^0.13.5
  flutter_speed_dial: ^1.2.5
  flutter_bloc: ^4.0.0
  equatable: ^1.1.1
  moor: ^2.4.2
  moor_ffi: ^0.4.0
  audioplayers: ^0.15.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator: ^2.4.0
  build_runner:

flutter:
  uses-material-design: true
  
  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/data.json
   - assets/db/jp.db
   - assets/png/menu.png
   - assets/listening.png
   - assets/onbarad1.png
   - assets/onbarad2.png
   - assets/png/appbar2.png
   - assets/audio_0.lrc
   - assets/audio_0.mp3
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
